### ISSUE TITLE
Different genders support

### ISSUE THREAD

**Issue by GraninNikita** [AndrewStarWind/req-generator-vercel#1]
There are many different gender identities, including male, female, transgender, gender-neutral, non-binary, agender, pangender, genderqueer, two-spirit, third gender, and all, none or a combination of these.

There are many more gender identities. Gender can be complex and people are defining themselves in new and different ways as we gain a deeper understanding of identities. Some terms may mean different things to different people. There are certain terms some folks may not like to use or call themselves and some terms that they may like to use or call themselves. If you’re not sure what to call a person, it’s best to ask the person what they would like to be called.  It is always up to us to decide how we identify, and how we express our gender. However, you decide or identify deserves to be respected and supported.

**Comment by AndrewStarWind** [comment]
Agreed. It’s regulates by Kazakhstan government. So I can do nothing about it. But you can surely direct them your thoughts.
